services:
  backend:
    volumes:
      - ./backend:/app/backend:cached
      - ./frontend_build:/app/frontend_build:cached
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DEBUG=true

  frontend:
    volumes:
      - ./frontend:/frontend:cached
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  worker:
    volumes:
      - ./backend:/app/backend:cached
    command: celery -A backend.worker.celery worker --loglevel=info
